### PR TITLE
Adapt styling to fix broken truncation

### PR DESCRIPTION
**Pull request by stffffn**
The truncation wasn't working which lead to a broken layout on mobile devices.  
I adapted the styling to fix the broken truncation and also introduced some minor improvements for the mobile view without changing your initial styling too much:

- Using gaps instead of the `space-y` utility class: Adds a gap between the avatar and the name/handle & removes the one-sided margin on the left
- Uniform padding on the sides
- Actually centering avatar and follow button

### Mobile view example:
| before-1 | after-1 |
|:---:|:---:|
| Before | After |

### Another mobile view example:
| before-2 | after-2 |
|:---:|:---:|
| Before | After |

### Desktop view is visually unchanged:
| before-3 | after-3 |
|:---:|:---:|
| Before | After |

(Currently also includes formatting changes - see https://github.com/gabipurcaru/followgraph/pull/11)

### CODE REVIEW

**Comment by gabipurcaru** [comment]
Hey @stffffn, thanks for the PR. Yes, I see the problem here. I'm not entirely sure that truncating the text is the way to go though, since the information in there should be visible. A better solution would be to split the `${handle} | ${num} followers` in two lines on narrow width screens.

Can you change the PR to do that? Thanks!

**Review by gabipurcaru — CHANGES_REQUESTED** [review]
requesting changes, as per comment

**Comment by stffffn** [comment]
> Hey @stffffn, thanks for the PR. Yes, I see the problem here. I'm not entirely sure that truncating the text is the way to go though, since the information in there should be visible. A better solution would be to split the `${handle} | ${num} followers` in two lines on narrow width screens.
> 
> Can you change the PR to do that? Thanks!

Sure, will do 👍   
I actually thought the same but didn't want to introduce such changes unsolicited and just wanted to make the originally implemented behavior work.

**Comment by stffffn** [comment]
I have kept the `truncate` utility class just for the handle to deal with very long edge cases, since I don't think that using word breaks would be a good solution.

### New:


### Fictional edge case:


### Visually still unchanged by the changes:

**Review by gabipurcaru — APPROVED** [review]
looks great! Thanks @stffffn!

**Pull request merged**
